version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "$DB_USERNAME"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
      POSTGRES_DB: "$DB_DATABASE"
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  # web:
  #   build: .
  #   command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  #   volumes:
  #     - .:/myapp
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
